update testing.yml file, add waiting postgres script

diff --git a/.github/workflows/test.yml b/.github/workflows/test.yml
--- a/.github/workflows/test.yml
+++ b/.github/workflows/test.yml
@@ -24,7 +24,15 @@ jobs:
       - name: Wait for DB to be ready
         run: |
           echo "Waiting for Postgres to be ready..."
-          sleep 15
+          run: |
+            echo "Waiting for Postgres connection..."
+            for i in {1..20}; do
+                nc -z postgres-db 5432 && echo "Postgres is up!" && exit 0
+                echo "Postgres not ready yet... ($i)"
+                sleep 5
+            done
+            echo "Failed to connect to Postgres after 100 seconds"
+            exit 1
 
       - name: Run Prisma Migrate (ensure DB is ready)
         env:
